# Generated by Django 5.0.7 on 2024-08-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_status'),
        ('exercises', '0001_initial'),
        ('lessons', '0006_alter_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercises', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='exercises', to='lessons.lesson'),
        ),
    ]
