# Generated by Django 5.0.7 on 2024-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_slug_alter_exercise_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
