# Generated by Django 5.0.7 on 2024-08-16 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_name'),
        ('lessons', '0006_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise', to='lessons.lesson'),
        ),
    ]
