# Generated by Django 5.0.7 on 2024-07-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images')),
                ('course_format', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('text_and_video', 'Text And Video')], default='text', max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='levels.level')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
