# Generated by Django 5.0.7 on 2024-08-03 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['encryption_techniques', 'hashing_algorithms', 'digital_forensics'], 'model__in': ['encryptiontechnique', 'hashingalgorithm', 'digitalforensic']}, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
    ]
