# Generated by Django 5.0.7 on 2024-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor_alter_course_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15),
        ),
    ]
