# Generated by Django 5.0.7 on 2024-07-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_topic_quizzes', '0002_initial'),
        ('course_topics', '0002_initial'),
        ('courses', '0001_initial'),
        ('exercises', '0001_initial'),
        ('lesson_quizzes', '0001_initial'),
        ('lessons', '0001_initial'),
        ('user_progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursequizzes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course'),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercoursetopicquizzes',
            name='course_topic_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='course_topic_quizzes.coursetopicquiz'),
        ),
        migrations.AddField(
            model_name='usercoursetopicquizzes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercoursetopics',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='course_topics.coursetopic'),
        ),
        migrations.AddField(
            model_name='usercoursetopics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexercises',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='userexercises',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlessonquizzes',
            name='lesson_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lesson_quizzes.lessonquiz'),
        ),
        migrations.AddField(
            model_name='userlessonquizzes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlessons',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='userlessons',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
