# Generated by Django 5.0.7 on 2024-08-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_topics', '0003_alter_coursetopic_course'),
        ('courses', '0002_course_instructor_alter_course_content_type'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_topics.coursetopic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lessons', to='courses.course'),
        ),
    ]
