# Generated by Django 5.0.7 on 2024-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_course_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_format',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF'), ('text_and_video', 'Text And Video'), ('video_link', 'Video Link')], default='text', max_length=15),
        ),
    ]
