# Generated by Django 5.0.7 on 2024-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_duration_lesson_lesson_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
