# Generated by Django 5.0.7 on 2024-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_lesson_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
