# Generated by Django 5.0.7 on 2024-07-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_topics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course'),
        ),
    ]
