# Generated by Django 5.0.7 on 2024-08-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_topics', '0002_initial'),
        ('courses', '0002_course_instructor_alter_course_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_topics', to='courses.course'),
        ),
    ]
