# Generated by Django 5.0.7 on 2024-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_topics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
