# Generated by Django 5.0.7 on 2024-07-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_topic_quizzes', '0001_initial'),
        ('course_topics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopicquiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursetopicquiz',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_topics.coursetopic'),
        ),
    ]
