# Generated by Django 5.0.7 on 2024-08-16 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_topic_quizzes', '0002_initial'),
        ('course_topics', '0003_alter_coursetopic_course'),
        ('courses', '0003_course_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopicquiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_quizzes', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursetopicquiz',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_quizzes', to='course_topics.coursetopic'),
        ),
        migrations.AlterField(
            model_name='coursetopicquiz',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coursetopicquiz',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
