# Generated by Django 5.0.7 on 2024-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquiz',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonquiz',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
